version: '2'
services: 
    web: 
        image: ubuntu/nginx
        ports:
            - "8181:80"
        volumes:
            - ./app:/data/www/
            
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            
            - ./docker/nginx/log/error.log:/var/log/nginx/error.log
            - ./docker/nginx/log/access.log:/var/log/nginx/access.log
        links:
            - phpfpm:phpfpm
            - mysql:db
    phpfpm:
        build: 
            context: ./docker/dockerfile/php
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./app:/data/www/
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306" 
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/data/:/data/import/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql:db
        ports:
            - "8183:80"
        environment:
            PMA_USER: root
            PMA_PASSWORD: admin
            PMA_ARBITRARY: 1
