<?php echo ($this->doctype()) ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo ($this->headTitle('PokeAdmin')->setSeparator(' - ')->setAutoEscape(false)) ?>

        <?php echo($this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'))
        ?>

        <!-- Le styles -->
        <?php echo ($this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css')))
        ?>

        <!-- Scripts -->
        <?php echo($this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js')))
        ?>
    </head>
    <body>
        <div class="header">
            <?php echo($this->render('header.phtml')); ?>
        </div>
        <div class="container">
            <?php echo($this->content) ?>
        </div>
        <div class="footer">
            <?php echo($this->render('footer.phtml')); ?>
        </div>
        <?php echo($this->inlineScript()) ?>
    </body>
</html>
