<!doctype html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta content="Tinwork API Pokemon" property="og:title">
    <meta content="API Pokemon application build with Zend Framework 3." name="description">

    <title>Tinwork API Pokemon</title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src='https://cdn.rawgit.com/rstacruz/flatdoc/v0.9.0/legacy.js'></script>
    <script src='https://cdn.rawgit.com/rstacruz/flatdoc/v0.9.0/flatdoc.js'></script>

    <link  href='https://cdn.rawgit.com/rstacruz/flatdoc/v0.9.0/theme-white/style.css' rel='stylesheet'>
    <script src='https://cdn.rawgit.com/rstacruz/flatdoc/v0.9.0/theme-white/script.js'></script>

    <!-- Initializer -->
    <script>
        Flatdoc.run({
            //fetcher: Flatdoc.file('README.md')
            fetcher: Flatdoc.github('Tinwork/ZendPokemon')
        });
    </script>
</head>
<body role='flatdoc'>
    <div class='header'>
        <div class='left'>
            <h1>Tinwork API Pokemon</h1>
            <ul>
                <li><a href='https://github.com/Tinwork/ZendPokemon'>View on GitHub</a></li>
                <li><a href='https://github.com/Tinwork/ZendPokemon/issues'>Issues</a></li>
            </ul>
        </div>
        <div class='right'>
            <!-- GitHub buttons: see http://ghbtns.com -->
            <iframe src="http://ghbtns.com/github-btn.html?user=Tinwork&amp;repo=ZendPokemon&amp;type=watch&amp;count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe>
        </div>
    </div>
    <div class="content-root">
        <div class='menubar'>
            <div class='menu section' role='flatdoc-menu'></div>
        </div>
        <div role='flatdoc-content' class='content' style="width: 100%!important; max-width: none!important;"></div>
    </div>
</body>
</html>